name: post_now_fleet
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.5.2+1
  firebase_analytics: ^6.2.0
  firebase_auth: ^0.18.3+1
  firebase_messaging: ^7.0.3
  firebase_core_web: ^0.2.1+1
  firebase_database: ^4.3.0
  firebase_storage: ^5.1.0
  cloud_firestore: ^0.14.3+1

  cupertino_icons: ^0.1.3
  http: ^0.12.2
  google_maps_webservice: ^0.0.17
  google_maps_flutter: ^0.5.28+1
  google_map_polyline: ^0.2.0+1
  flutter_google_places: ^0.2.6
  permission_handler: ^5.0.1+1
  geolocator: ^5.3.2+2
  image_picker: ^0.6.7+4
  path_provider: ^1.6.11
  path: ^1.6.4
  easy_localization: ^2.3.3
  characters: ^1.0.0
  screen: ^0.0.5
  package_info: ^0.4.3
  url_launcher: ^5.6.0
  flutter_inappwebview: ^4.0.0+4
  store_redirect: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/map_styles/
    - assets/translations/
    - assets/sounds/
    - assets/licances/